spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://localhost:3306/blogDB
    username: root1234
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 888f3c36463be6ada1fbfc85edac0232
            client-secret: UuNXMl0eyDf8JMPlTWoU5BiN1AOvzHj6
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - profile_nickname

          naver:
            client-id: 3a_Puh_atCEjQRdro0ry
            client-secret: FyiSA5KCZP
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

          google:
            client-id: 861525290723-fmnvsh0aklong8hc5t2krfnsj01pl5ni.apps.googleusercontent.com
            client-secret: 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
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  mail:
    host: smtp.gmail.com
    port: 587
    username: ch9800113@gmail.com
    password: edck rqay htcz nzrk
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

server:
  port: 8081

file:
  upload-dir: src/main/resources/static/files/

# oauth
