name: Deploy to EC2 # 1 깃허브 액션 이름 변경

on:
  push:
    branches:
      - main # 2 배포할 브랜치 지정

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 3 실행 환경
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 21 # 4 현재 프로젝트의 버전
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Build with Gradle
        run: |
          chmod 755 ./gradlew
          ./gradlew build

      - name: Prepare deployment package
        run: |
          cd deployment
          zip -r deployment.zip appspec.yml scripts/
          mv deployment.zip ../
          cd ..
          zip -r deployment.zip -g build/libs/blog-0.0.1-SNAPSHOT.jar

      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - run: aws s3 cp deployment.zip s3://blog-build-files/

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name blog \
            --deployment-group-name blog-group \
            --s3-location bucket=blog-build-files,key=deployment.zip,bundleType=zip
