name: Deploy to EC2 # 1 깃허브 액션 이름 변경

on:
  push:
    branches:
      - dev # 2 배포할 브랜치 지정

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 3 실행 환경
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21 # 4 현재 프로젝트의 버전
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: chmod +x gradlew
        uses: gradle/gradle-build-action@v2.6.0
        with:
            arguments: build

      - name: List build directory
        run: ls -la build/libs

      # 빌드해서 생긴 JAR 파일을 깃허브 아티팩트로 업로드
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
             name: blog-0.0.1-SNAPSHOT
             path: build/libs/blog-0.0.1-SNAPSHOT.jar

      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - run: aws s3 cp deployment.zip s3://blog-build-files/

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name blog \
            --deployment-group-name blog-group \
            --s3-location bucket=blog-build-files,key=deployment.zip,bundleType=zip
