POST http://localhost:80/api/login
Content-Type: application/json

{
  "userName": "iam",
  "password": "1234"
}

###
GET http://localhost:80/api/authtest
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpYW1AbmF2ZXIuY29tIiwidXNlcklkIjoyOCwidXNlcm5hbWUiOiJpYW0iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIwNzY5NzQwLCJleHAiOjE3MjA3NzE1NDB9.EtzGWkE2Yg4KXPZfPMSCes506MiyOoEOyhViI9YqM5c


###
GET http://localhost:80/api/authtest
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpYW1AbmF2ZXIuY29tIiwidXNlcklkIjoyOCwidXNlck5hbWUiOiJpYW0iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIwNjc0OTA0LCJleHAiOjE3MjA2NzY3MDR9.own7xlLJD8Ej_HQi4wAvlU2_q3ZPOxUkHQFPRRgHx3I

###
# @no-cookie-jar
GET http://localhost:80/api/authtest

###
POST http://localhost:80/api/refreshToken
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJxcXFxQG5hdmVyLmNvbSIsInVzZXJJZCI6MTksInVzZXJuYW1lIjoicXFxcSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpYXQiOjE3MjA2NjMwNzIsImV4cCI6MTcyMTI2Nzg3Mn0.mdkSI6bQ4MDfzjOCAbvuMWCbGPP0y-2vcyqkJz8YQ6E

###
GET http://localhost:80/api/logout
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpYW1AbmF2ZXIuY29tIiwidXNlcklkIjoyOCwidXNlcm5hbWUiOiJpYW0iLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNzIwNjY4NDQxLCJleHAiOjE3MjA2NzAyNDF9.VY84-Ll5jfguk03y1n1hf0nJCGRfRkFBSJuZnBHOdYE